### ISSUE TITLE
HyperCP installation fail

### ISSUE THREAD

**Issue by samanthalsharp** [nasa/HyperInSPACE#268]
I'm having trouble installing HyperCP on my computer. I am stuck initializing the python environment "conda env create -f environment.yml." I have revised the environmentl.yml file to not require a specific version of py6s, which was identified as an issue during the Ocean Optics workshop. But there still appear to be a number of conflicts (see attached output). 
[HyperCP_install_attempt.txt](https://github.com/user-attachments/files/17576932/HyperCP_install_attempt.txt)

I have a Dell Precision 3560 laptop with Intel Core i7 processor, Windows 10 Enterprice, Python version 3.9.12 and Anaconda version 2022.05. 

Please let me know if you have any suggestions

**Comment by oceancolorcoder** [comment]
Sorry for the delay. I am just getting back from vacation and will look into your environment issue as soon as possible.
-Dirk

**Comment by samanthalsharp** [comment]
No worries and thanks for your help Dirk! I would like to get started
processing my data through HyperCP but have been stuck with this
installation issue since the Ocean Optics workshop.

Thanks,
Samantha

**Comment by oceancolorcoder** [comment]
@samanthalsharp, please try the following.

First, uninstall the hypercp environment:
`conda remove -n hypercp --all`

Next, reinstall (from HyperCP directory):
`conda env create -f environment.yml`

I just tested on my windows 11 PC and it took ~10 minutes to build. If this does not work, please try to install the environment using mamba. Download for Windows 64 bit is available here: https://github.com/conda-forge/miniforge. Once installed, open the Miniforge Prompt app from the Search bar and from the HyperCP directory:
`mamba env create -f environment.yml`

Due to licensing issues, we will be moving to encourage users to use mamba in the future to build the hypercp enviroment. 

Hope this helps!

I tested this also on Win11 and it was slightly faster.

**Comment by oceancolorcoder** [comment]
Nothing heard. Closing.

**Comment by samanthalsharp** [comment]
Hi Dirk,

Sorry for the late reply, I was at a conference and did not manage to
reply. I followed your instructions and get stuck on "solving environment"
seemingly forever. If I restart the miniforge prompt and try to activate
the environment, it cannot find hypercp. I'm not sure why this is not
working but I am getting a new laptop in the next couple of weeks so I
think I will try again then to see if I can get hypercp working.

Thanks,
Samantha
